import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";

import "./globals.css";
import Layout from "./(client)/layout";
import { UserProvider } from "./user-provider";
import { cn } from "@/lib/utils";
import { CartProvider } from "@/context/CartContext";
import { CartPopup } from "./component/cart-popup";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <UserProvider />
          {children}
          <CartPopup />
        </CartProvider>
      </body>
    </html>
  );
}
